site:
  title: Trang Nguyen
  # description: AP in Statistics

author:
  name: Trang Nguyen
  email: thidaitrang.nguyen@sdstate.edu
  avatar: "/img/avatar-icon.jpg"

navbar-links:
  '<i class="far fa-newspaper"></i> Publications': "#publications"
  '<i class="fas fa-book-open"></i> Teaching': "#teaching"
  '<i class="fas fa-microscope"></i> Conferences': "#conferences"
  '<i class="fas fa-award"></i> Awards': "#award"
  '<i class="fas fa-plus"></i> Activities': "#activities"
  # more:
  #   - '<i class="fas fa-plus"></i> Activities': "#activities"


nBooks: 4 # number of books showed in reading list (must be devisor of 12)
nPosts: 8 # number of posts showed in latest posts
# nPhotos: 8 # number of photos in latest sketches

# size-lg: "col-sm-10 col-sm-offset-1 col-12" # bigger size width
# size-md: "col-sm-8 col-sm-offset-2 col-12" # smaller size width (in comp with size-lg)
size-lg: "col-12" # bigger size width
size-md: "col-12" # smaller size width (in comp with size-lg)
